### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by chen-zhuohan** [tikv/protobuf-build#44]
When I build(just as down), the error happen.

PS C:\Project\raft_kv> cargo build
   Compiling protobuf-build v0.8.0
   Compiling protobuf-build v0.10.0
error[E0425]: cannot find function `generate` in this scope
  --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\protobuf-build-0.8.0
\src\lib.rs:35:5
   |
35 |     generate(includes, files, out_dir);
   |     ^^^^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `protobuf-build`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0599]: no method named `generate_files` found for reference `&Builder` in the current scope
  --> C:\Users\Administrator\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\protobuf-build-0.10.
0\src\lib.rs:56:14
   |
56 |         self.generate_files();
   |              ^^^^^^^^^^^^^^ method not found in `&Builder`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: build failed

```toml
[package]
name = "raft_kv"
version = "0.1.0"
authors = ["Administrator <chen_zhuohan@163.com>"]
edition = "2018"

[dependencies]
raft = { version = "0.6.0-alpha", default-features = false }
protobuf = "2"
regex = "1"
protobuf-build = { version = "0.10", default-features = false }
slog = "2.2"
#[build-dependencies]
#protobuf-build = { version = "0.11", default-features = false }

```
